/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'weli' at '4/29/17 1:09 AM' with Gradle 2.14.1
 *
 * @author weli, @date 4/29/17 1:09 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
